export type Provincia  = {
  IN_POLIZAS: boolean;
  ID_PROVINCIA: number;
  NO_PROVINCIA: string;
  CO_PROVINCIA: string;
  LST_ACTIVIDADES: any[];
  CO_ISO: string;
  IS_NEW: boolean;
  IS_UPDATED: boolean;
  IS_DELETED: boolean;
  IS_SELECTED: boolean;
  IS_UNIDENTIFIED: boolean;
  IS_ERROR: boolean;
  IS_WARN: boolean;
  IS_HISTORICO: boolean;
  IS_TACITA: boolean;
  IS_CONDICIONADO: boolean;
  PAGINAR: boolean;
  OFFSET: number;
  LIMIT: number;
  aseguradora: string;
};
